"""initial schema

Revision ID: 44a4dc400c9c
Revises: 
Create Date: 2026-10-04 18:18:24.652811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a4dc400c9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('render_mode', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_cache_url_hash'), ['url_hash'], unique=True)

    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('official_url', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('name_chinese', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universities_domain'), ['domain'], unique=True)

    op.create_table('research_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('university_url', sa.String(length=1024), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('requester_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_jobs_university_id'), ['university_id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_chinese', sa.String(length=512), nullable=True),
    sa.Column('school', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('faculty_list_urls', sa.JSON(), nullable=False),
    sa.Column('matched_fields', sa.JSON(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_job_id'), ['job_id'], unique=False)

    op.create_table('research_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('supports', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index('ix_sources_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_job_id'), ['job_id'], unique=False)

    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_chinese', sa.String(length=64), nullable=True),
    sa.Column('name_is_romanized', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('position_original', sa.String(length=128), nullable=True),
    sa.Column('department_name', sa.String(length=512), nullable=True),
    sa.Column('school', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_status', sa.String(length=32), nullable=False),
    sa.Column('profile_url', sa.String(length=1024), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verification_checks', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professors_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_professors_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_professors_job_name', ['job_id', 'name'], unique=False)

    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('student_profile', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=32), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_drafts_professor_id'), ['professor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_drafts_professor_id'))

    op.drop_table('email_drafts')
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.drop_index('ix_professors_job_name')
        batch_op.drop_index(batch_op.f('ix_professors_job_id'))
        batch_op.drop_index(batch_op.f('ix_professors_email'))

    op.drop_table('professors')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_job_id'))
        batch_op.drop_index('ix_sources_entity')

    op.drop_table('sources')
    op.drop_table('research_results')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_job_id'))

    op.drop_table('departments')
    with op.batch_alter_table('research_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_jobs_university_id'))
        batch_op.drop_index(batch_op.f('ix_research_jobs_status'))

    op.drop_table('research_jobs')
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_domain'))

    op.drop_table('universities')
    with op.batch_alter_table('page_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_cache_url_hash'))

    op.drop_table('page_cache')
    # ### end Alembic commands ###
